### ISSUE TITLE
cdaf/WindowsServerDC: Packer sources

### ISSUE THREAD

**Issue by danielmenezesbr** [cdaf/windows#17]
Could you share the packer sources that generate [cdaf / WindowsServerDC](https://app.vagrantup.com/cdaf/boxes/WindowsServerDC/versions/2020.05.14)?

**Comment by cdaf** [comment]
Hi, I've not used Packager, just simple powershell scripts, see the following in the root of the repo. The domain controller itself

AtlasBase.ps1

prepare the image for Vagrant in Hyper-V and VirtualBox

AtlasImage.ps1

Package for app.vagrantup.com

AtlasPackage.ps1

**Comment by danielmenezesbr** [comment]
Thanks!
